services:
  bd-navy-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bd-navy-hydrography-frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000

    env_file:
      - .env
    restart: unless-stopped